<?php
$this->title = "Delete Role";
$this->headTitle($this->title);
?>
<p>¿ Estas seguro de que quieres eliminar el rol "
    '<?php echo $this->escape($this->role['role_name']); ?>' " es probocara eliminar todos los usuarios con ese rol
    
</p>
<form action="<?php echo $this->url(array('action' => 'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->role['id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>
