<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Roles")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'role',
    'action' => 'add')); ?>">Add new role</a></p>
        <ul id="topbtns">
            <li>
                <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'role', 'action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_calendar.png" alt="Role" /><br />role</a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'index', 'action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_user.png" alt="Users" /><br />Users</a>

            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'permission', 'action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_create.png" alt="Permission" /><br />Permission  </a>
            </li>
           
            <li>
                <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'resource', 'action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_support.png" alt="Resource" /><br />Resource</a>
            </li>                
        </ul>

    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>

                    <th><?php echo $this->translate('Name'); ?></th>
                    <th><?php echo $this->translate('Role Parent'); ?></th>
                    <th><?php echo $this->translate('Prefered Uri'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->paginator as $role) : ?>
                    <?php if($role["name"] != 'implementor') {?>
                    <tr>
                        
                        <td><?php echo $this->escape($role["name"]); ?></td>
                        <td><?php echo $this->escape($role["parents_name"]); ?></td>
                        <td><?php echo $this->escape($role["prefered_uri"]); ?></td>

                        <td>
                            <a href="<?php echo $this->url(array('controller' => 'role', 'action' => 'edit', 'id' => $role["id"])); ?>">
                                <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'role', 'action' => 'delete', 'id' => $role["id"])); ?>">
                                <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                        </td>
                    </tr>
                    
                <?php }
                endforeach; ?>
        </table>
        <div class="extrabottom">
            <?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
