          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Users")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'user',
    'action' => 'add')); ?>">Add new user</a></p>
       
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>
                    
                </tr>
                                    
                <tr>
                    <th><?php echo $this->translate('User name'); ?></th>
                    <th><?php echo $this->translate('Date'); ?></th>
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('Status'); ?></th>
                    <th><?php echo $this->translate('Person_id?'); ?></th>
                    <th><?php echo $this->translate('Validation code'); ?></th>
                    <th><?php echo $this->translate('Phone'); ?></th>
                    <th><?php echo $this->translate('Role'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>
                    
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->paginator as $user) : ?>
                    <tr>
                        <td><?php echo $this->escape($user->name); ?></td>                         
                        <td><?php echo $this->escape($user->date); ?></td>
                        <td><?php echo $this->escape($user->email); ?></td>
                        <td><?php echo $this->escape($user->status); ?></td>
                        <td><?php echo $this->escape($user->person_id); ?></td>
                        <td><?php echo $this->escape($user->validation_code); ?></td>
                        <td><?php echo $this->escape($user->phone); ?></td>
                        <td><?php echo $this->escape($user->role); ?></td>               
                        <td>
                            <a href="<?php echo $this->url(array('controller' => 'user','action' => 'edit', 'id' => $user->id)); ?>">
                            	<img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'user','action' => 'delete', 'id' => $user->id)); ?>">
                            	<img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                        </td>                        
                    </tr>
                <?php endforeach; ?>
        </table>
       <div class="extrabottom">
            <?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  
