<?php
$this->title = "Delete Permissionproduction";
$this->headTitle($this->title);
?>
<p>Are you sure that you want to delete
    
    '<?php $this->production= new Zend_Session_Namespace('production');
            
    echo $this->escape($this->production->name); 
     ?>' by
    
</p>
<form action="<?php echo $this->url(array('action' => 'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->permissionproduction['id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>
