<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Permissions")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'permission',
    'action' => 'add')); ?>">Add new permission</a></p>
         

    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>
                    
                    <th><?php echo $this->translate('Permission'); ?></th>
                    <th><?php echo $this->translate('Name'); ?></th>
                    <th><?php echo $this->translate('Menu'); ?></th>
                    <th><?php echo $this->translate('Role'); ?></th>
                    <th><?php echo $this->translate('Resource'); ?></th>
                    <th><?php echo $this->translate('Actions');?></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->paginator as $permission) : ?>
                    <tr>
                
                        <td><?php echo $this->escape($permission->permission); ?></td>
                        <td><?php echo $this->escape($permission->name); ?></td>
                        <td><?php echo $this->escape($permission->menu); ?></td>
                        <td><?php echo $this->escape($permission->role); ?></td>
                        <td><?php echo $this->escape($permission->resource); ?></td>
                        
                        <td>
                            <a href="<?php echo $this->url(array('controller' => 'permission','action' => 'edit', 'id' => $permission->id)); ?>">
                            	<img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'permission','action' => 'delete', 'id' => $permission->id)); ?>">
                            	<img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
        </table>
       
        <div class="extrabottom">
            <?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  
