<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Resources")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'resource',
    'action' => 'add')); ?>">Add new resource</a></p>
        

    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>

                    <th><?php echo $this->translate('Resource'); ?></th>
                    <th><?php echo $this->translate('Resource Name'); ?></th>
                    <th><?php echo $this->translate('module'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->paginator as $resource) : ?>
                    <tr>

                        <td><?php echo $this->escape($resource->resource); ?></td>
                        <td><?php echo $this->escape($resource->name_r); ?></td>
                        <td><?php echo $this->escape($resource->module); ?></td>

                        <td>
                            <a href="<?php echo $this->url(array('controller' => 'resource', 'action' => 'edit', 'id' => $resource->id)); ?>">
                                <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'resource', 'action' => 'delete', 'id' => $resource->id)); ?>">
                                <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                        </td>

                    </tr>
                <?php endforeach; ?>
        </table>
        <div class="extrabottom">
            <div class="extrabottom">
                <?php echo $this->paginator; ?>           
            </div>
           
        </div>
    </div>
</div>

