<div class="row">
	<label><?=$this->translate($this->element->getLabel());?></label>
	<div class="inputs">		
		<span class="input_wrapper select_wrapper">
			<?php echo $this->{$this->element->helper}(
								        $this->element->getName(),
								        $this->element->getValue(),
								        $this->element->getAttribs(),
								        $this->element->getMultiOptions()
								    ) ?>
		</span>
		<span class="system negative"><?php echo $this->formErrors($this->element->getMessages()) ?></span>
		<div class="hint"><?php echo $this->element->getDescription() ?></div>
	</div>
</div>