<?php
if ($this->element->getMessages()) {
    $this->element->class.=" errorbox";
};
?>
 <?php //TODO crear el element->getImages?>
<div class="inputcontainer">
 
  
   <!--<img src="/styles/images/icons/icon_username.png" alt="Username" />-->
    <label for="username"><?=$this->translate($this->element->getLabel());?>:</label>
    <?= $this->{$this->element->helper}(
                $this->element->getName(),
                $this->element->getValue(),
                $this->element->getAttribs()
    ) ?>
    <?php if ($this->element->hasErrors()): ?>
        <?php echo $this->formErrors($this->element->getMessages()) ?>
<?php endif; ?> 
    <!-- Classes for input-notification: success, error, information, attention -->
<?php echo $this->element->getDescription() ?>

</div>

