<div class="inputboxes">
	 
	<div class="inputs">
		<?php echo $this->{$this->element->helper}(
                                    $this->element->getName(),
                                    $this->element->getValue(),
                                    $this->element->getAttribs(),
                                    $this->element->getMultiOptions(),
                                    "&nbsp;\n"
                                ) ?>
		 
		 
	</div>
</div>
