<div id="loginForm">
    <div id="login-top"></div>
    <div id="login-content">
        <table class="loginForm table-middle" cellpadding="2" cellspacing="2">
            <tr><td>
                    <h1>Error</h1>
                    <h3>Acceso Denegado</h3>
                    <!-- Green Status Bar Start -->
                    <div class="status error">
                        <p class="closestatus"><a href="" title="Close">x</a></p>
                        <p><img src="images/icons/icon_error.png" /> Está tratándo de acceder a un área restringida.</p>
                    </div>
                    <!-- Green Status Bar End -->
                </td></tr>
            <tr><td>

                    <?= $this->form ?>
                </td></tr></table>
    </div>
    <div id="login-bottom"></div>
</div>

