<div id="loginForm">
    <div id="login-top"></div>
    <div id="login-content">
        <table class="loginForm table-middle" cellpadding="2" cellspacing="2">
            <tr><td>
                    <h1>Error</h1>
                    <h3>Acceso Denegado</h3>
                    <p class="error">Pagina no encontrado 404.</p>
                </td></tr>
            <tr><td>

                    <?= $this->form ?>
                </td></tr></table>
    </div>
    <div id="login-bottom"></div>
</div>