<?php $acl = Login_Model_Acl::getInstance(); ?>
<!-- Table activity end -->  
<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Activity")); ?></h1>
       
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                 
                <tr>
                    <th><?php echo $this->translate('Name'); ?></th>
                    <th><?php echo $this->translate('Activity types'); ?></th>
                    <th><?php echo $this->translate('Contact Client'); ?></th>
                    <th><?php echo $this->translate('Contact Company'); ?></th>
                    <th><?php echo $this->translate('Date start'); ?></th>
                    <th><?php echo $this->translate('Date end'); ?></th>
                    <th><?php echo $this->translate('Type'); ?></th> 
                    <th><?php echo $this->translate('Status'); ?></th>
                </tr>
            </thead>

            <tbody>
              
                        <tr>
                            <td><?php echo $this->escape($this->activity["name"]); ?></td>
                            <td><?php echo $this->escape($this->activity["activity_type_name"]); ?></td>
                            <td><?php echo $this->escape($this->activity["contact_client_company_name"]); ?></td>
                            <td><?php echo $this->escape($this->activity["contact_own_company_name"]); ?></td>
                            <td><?php echo $this->escape($this->activity["date_start"]); ?></td>
                            <td><?php echo $this->escape($this->activity["date_end"]); ?></td>
                            <td><?php echo $this->escape($this->activity["status"]); ?></td>
                            <td>
                                
                                 <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:activity", "edit")) { ?>
                             
                                <a href="<?php echo $this->url(array('controller' => 'activity', 'action' => 'edit')); ?>">
                                    <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                                  <?php } ?>
                                
                                <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:activity", "delete")) { ?>
                             
                                <a href="<?php echo $this->url(array('controller' => 'activity', 'action' => 'delete')); ?>">
                                    <img src="/styles/images/icons/icon_delete.png" alt="Edit" /></a>
                                  <?php } ?>
                            </td>
                            
                        </tr>         
                      
        </table>
        <div>
        
        </div>   
    </div>
    
</div>
<!-- Table activity end -->  


<!-- Table resource -->  
<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Activity Resources")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'resource',
    'action' => 'add'));
?>">Add new resource</a></p>

    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
         
                <tr>
                    <th><?php echo $this->translate('name'); ?></th>
                    <th><?php echo $this->translate('resource'); ?></th>
                    <th><?php echo $this->translate('supplier'); ?></th>
                    <th><?php echo $this->translate('supplier contact'); ?></th>
                    <th><?php echo $this->translate('unbilled hours'); ?></th>
                    <th><?php echo $this->translate('observation'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php if ($this->paginator) {
                    foreach ($this->paginator as $resource) :
                        ?>
                        <tr>
                            <td><?php echo $this->escape($resource->name); ?></td>
                            <td><?php echo $this->escape($resource->resource_name); ?></td>
                            <td><?php echo $this->escape($resource->supplier_name); ?></td>
                            <td><?php echo $this->escape($resource->supplier_contact_name); ?></td>
                            <td><?php echo $this->escape($resource->unbilled_hours); ?></td>
                            <td><?php echo $this->escape($resource->observation); ?></td>
                            <td>
                                <a href="<?php echo $this->url(array('controller' => 'resource', 'action' => 'edit', 'id' => $resource->id)); ?>">
                                    <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                                <a href="<?php echo $this->url(array('controller' => 'resource', 'action' => 'delete', 'id' => $resource->id)); ?>">
                                    <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                            </td>                        
                        </tr>
                <?php endforeach;
            } ?>
        </table>
        <div class="extrabottom">
<?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table resource end -->  
