          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Activitys")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'activity',
    'action' => 'add')); ?>">Add new activity</a></p>
        <ul id="topbtns">
            	<li>
                	<a href="<?php echo $this->url(array('module' => 'activity','controller' => 'role','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_calendar.png" alt="Role" /><br />role</a>
                </li>
                <li>
                        <a href="<?php echo $this->url(array('module' => 'activity','controller' => 'activity','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_user.png" alt="Activitys" /><br />Activitys</a>
                
                </li>
                <li>
                	<a href="<?php echo $this->url(array('module' => 'activity','controller' => 'permission','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_create.png" alt="Permission" /><br />Permission  </a>
                </li>
               
                <li>
                	<a href="<?php echo $this->url(array('module' => 'activity','controller' => 'resource','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_support.png" alt="Resource" /><br />Resource</a>
                </li>                
            </ul>
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>
                    
                </tr>
                                    
                <tr>
                    <th><?php echo $this->translate('production'); ?></th>
                    <th><?php echo $this->translate('activity_type'); ?></th>
                    <th><?php echo $this->translate('client'); ?></th>
                    <th><?php echo $this->translate('client_name'); ?></th>                   
                    <th><?php echo $this->translate('Actions'); ?></th>
                    
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->paginator as $activity) : ?>
                    <tr>
                        <td><?php echo $this->escape($activity->productions_id); ?></td>
                        <td><?php echo $this->escape($activity->activity_types_id); ?></td>
                        <td><?php echo $this->escape($activity->client); ?></td>
                        <td><?php echo $this->escape($activity->client_resp_name); ?></td>
                                      
                        <td>
                            
                            <a href="<?php echo $this->url(array('controller' => 'activity','action' => 'edit', 'id' => $activity->id)); ?>">
                            	<img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'activity','action' => 'delete', 'id' => $activity->id)); ?>">
                            	<img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                        </td>                        
                    </tr>
                <?php endforeach; ?>
        </table>
       <div class="extrabottom">
            <?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  
