          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Activitys")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'activity',
    'action' => 'add'));
?>">Add new activity</a></p>

    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                 
                <tr>
                    <th><?php echo $this->translate('Responsible'); ?></th>
                    <th><?php echo $this->translate('Activity_types'); ?></th>
                    <th><?php echo $this->translate('Client_resp_name'); ?></th>
                    <th><?php echo $this->translate('Date_start'); ?></th>
                    <th><?php echo $this->translate('Type'); ?></th> 
                    <th><?php echo $this->translate('Status'); ?></th>
                </tr>
            </thead>

            <tbody>
                <?php if ($this->paginator) {
                    foreach ($this->paginator as $activity) :
                        ?>
                        <tr>
                            <td><?php echo $this->escape($activity->name); ?></td>                         
                            <td>
                                <a href="<?php echo $this->url(array('controller' => 'activity', 'action' => 'edit', 'id' => $activity->id)); ?>">
                                    <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                                <a href="<?php echo $this->url(array('controller' => 'activity', 'action' => 'delete', 'id' => $activity->id)); ?>">
                                    <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                            </td>                        
                        </tr>
                <?php endforeach;
            } ?>
        </table>
        <div class="extrabottom">
<?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  
