<?php $acl = Login_Model_Acl::getInstance(); ?>          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Activitys")); ?></h1>
            <?php if (1){?>
        <p><a href="<?php echo $this->url(array('controller' => 'activity',
    'action' => 'add'));
?>">Add new activity</a></p>
<?php }?>
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                 
                <tr>
                    <th><?php echo $this->translate('Name'); ?></th>
                    <th><?php echo $this->translate('Activity_types'); ?></th>
                    <th><?php echo $this->translate('Client_resp_name'); ?></th>
                    <th><?php echo $this->translate('own_resp_name'); ?></th>
                    <th><?php echo $this->translate('Date_start'); ?></th>
                    <th><?php echo $this->translate('Date_end'); ?></th>
                    <th><?php echo $this->translate('Type'); ?></th> 
                    <th><?php echo $this->translate('Status'); ?></th>
                </tr>
            </thead>

            <tbody>
                <?php if ($this->paginator) {
                    foreach ($this->paginator as $activity) :
                        ?>
                        <tr>
                            <td><?php echo $this->escape($activity["name"]); ?></td>
                            <td><?php echo $this->escape($activity["activity_type_name"]); ?></td>
                            <td><?php echo $this->escape($activity["contact_client_company_name"]); ?></td>
                            <td><?php echo $this->escape($activity["contact_own_company_name"]); ?></td>
                            <td><?php echo $this->escape($activity["date_start"]); ?></td>
                            <td><?php echo $this->escape($activity["date_end"]); ?></td>
                            <td><?php echo $this->escape($activity["status"]); ?></td>
                            <td>
                                <a href="<?php echo $this->url(array('controller' => 'activity', 'action' => 'select', 'id' => $activity["id"])); ?>">
                                  Select</a>
                                <a href="<?php echo $this->url(array('controller' => 'activity', 'action' => 'delete', 'id' => $activity["id"])); ?>">
                                    <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                            </td>                        
                        </tr>
                <?php endforeach;
            } ?>
        </table>
        <div class="extrabottom">
<?php echo $this->paginator; ?>           
        </div>
    </div>
    
</div>
<!-- Table styles end -->  
