<?php
$this->title = "Delete Owncompany";
$this->headTitle($this->title);
?>
<p>Are you sure that you want to delete your own company
    '<?php echo $this->escape($this->owncompany['name']); ?>' by
    
</p>
<form action="<?php echo $this->url(array('action' => 'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->owncompany['id']; ?>" />
        <input type="hidden" name="company_id" value="<?php echo $this->owncompany['company_id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>
