<div class="container">
    <div class="conthead">
        <h2>Edit Own Company</h2>
    </div>
    <div id="idformcompany" class="contentbox">

        <?php
        echo $this->form;
        ?>

    </div>


</div>

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Contacts")); ?></h1>
        <p><a href="<?php
        echo $this->url(array('controller' => 'contact',
            'action' => 'add'));
        ?>">Add new contact</a></p>


        </p>
        <div id="iDformcontact" class="contentbox">

        </div>

    </div>



    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>

                </tr>

                <tr>
                    <th><?php echo $this->translate('Contact name'); ?></th>
                    <th><?php echo $this->translate('Status'); ?></th>
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('telephone'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->paginator as $contact) : ?>
                    <tr id="rowcontact<?php echo $contact->id; ?>">
                        <td><?php echo $this->escape($contact->name); ?></td>                         
                        <td><?php echo $this->escape($contact->status); ?></td>                         
                        <td><?php echo $this->escape($contact->email); ?></td>
                        <td><?php echo $this->escape($contact->telephone); ?></td>
                        <td>
                            <a href="<?php echo $this->url(array('controller' => 'contact', 'action' => 'edit', 'id' => $contact->id)); ?>">
                                <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'contact', 'action' => 'delete', 'id' => $contact->id)); ?>">
                                <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'contact', 'action' => 'inlitter', 'id' => $contact->id)); ?>">
                                <img src="/styles/images/icons/icon_in_litter.png" alt="Delete" /></a>
                            <a style='cursor: pointer;' onclick="getAjaxResponse('http://globalpms.es/company/contact/edit/id/<?php echo $contact->id; ?>/company_id/<?php echo $contact->company_id; ?>' ,'iDformcontact')">view form</a> 
                        </td>

                    </tr>

                <?php endforeach; ?>
        </table>
        <div class="extrabottom">
            <?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  