          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Own Companies")); ?></h1>
        
        <p><a href="<?php echo $this->url(array('controller' => 'owncompany',
           'action' => 'add'));?>">Add new own company <img src="/styles/images/icons/icon_plusgreen.png" /></a></p>
       
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>

                </tr>

                <tr>
                    <th><?php echo $this->translate('Company name'); ?></th>
                    <th><?php echo $this->translate('Fiscal name'); ?></th>
                    <th><?php echo $this->translate('Type'); ?></th>
                    <th><?php echo $this->translate('Telephone'); ?></th>
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('City'); ?></th>
                    <th><?php echo $this->translate('Description'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>
                    
                </tr>
                
            </thead>

            <tbody>
                    <?php foreach ($this->paginator as $owncompany) : ?>
                    <tr>
                        <td><?php echo $this->escape($owncompany->name); ?></td>                         
                        <td><?php echo $this->escape($owncompany->fiscal_name); ?></td>                         
                        <td><?php echo $this->escape($owncompany->company_types_name); ?></td>
                        <td><?php echo $this->escape($owncompany->telephone); ?></td>
                        <td><?php echo $this->escape($owncompany->email); ?></td>
                        <td><?php echo $this->escape($owncompany->city); ?></td>
                         <td><?php echo $this->escape($owncompany->description); ?></td>
                        <td>
                            <?php if ($owncompany->in_litter==0){?>
                            <a href="<?php echo $this->url(array('module' => 'production', 'controller' => 'production', 'action' => 'add', 'own_company_id' => $owncompany->id)); ?>">
                                <img src="/styles/images/icons/icon_claketa.png" alt="Añadir production" /></a>
                             <?php }?>
                            <a href="<?php echo $this->url(array('controller' => 'contact', 'action' => 'index', 'company_id' => $owncompany->company_id)); ?>">
                                <img src="/styles/images/icons/icon_user.png" alt="Consultar contactos" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'owncompany', 'action' => 'edit', 'own_company_id' => $owncompany->id)); ?>">
                                <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'owncompany', 'action' => 'delete', 'own_company_id' => $owncompany->id)); ?>">
                                <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                             <?php if ($owncompany['in_litter']==0){?>
                            <a href="<?php echo $this->url(array('controller' => 'company','action' => 'inlitter', 'id' => $owncompany->company_id)); ?>">
                            	<img src="/styles/images/icons/icon_in_litter.png" alt="Inlitter" /></a>
                            
                            <?php }else{?>
                            <a href="<?php echo $this->url(array('controller' => 'company','action' => 'outlitter', 'id' => $owncompany->company_id)); ?>">
                            	<img src="/styles/images/icons/icon_in_litter.png" alt="Oulitter" /></a>
                            <?php }?>
                        </td>                                       
                    </tr>
                    <?php endforeach; ?>
        </table>
        <div class="extrabottom">
<?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  
