          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Modeloejemplos")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'modeloejemplo',
    'action' => 'add'));
?>">Add new modeloejemplo</a></p>

    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
         
                <tr>
                    <th><?php echo $this->translate('name'); ?></th>

                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php if ($this->paginator) {
                    foreach ($this->paginator as $modeloejemplo) :
                        ?>
                        <tr>
                            <td><?php echo $this->escape($modeloejemplo->name); ?></td>                         
                            <td>
                                <a href="<?php echo $this->url(array('controller' => 'modeloejemplo', 'action' => 'edit', 'id' => $modeloejemplo->id)); ?>">
                                    <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                                <a href="<?php echo $this->url(array('controller' => 'modeloejemplo', 'action' => 'delete', 'id' => $modeloejemplo->id)); ?>">
                                    <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                            </td>                        
                        </tr>
                <?php endforeach;
            } ?>
        </table>
        <div class="extrabottom">
<?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  
