<?php $acl = Login_Model_Acl::getInstance(); ?>          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My supplier")); ?></h1>
        <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "supplier:supplier", "add")) { ?>
            <p><a href="<?php echo $this->url(array('controller' => 'supplier', 'action' => 'add'));
            ?>"><?php echo $this->translate("Add supplier") ?>

                </a></p>
        <?php } ?> 
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>

                <tr>
                    <th><?php echo $this->translate('name'); ?></th>

                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php
                if ($this->paginator) {
                    foreach ($this->paginator as $supplier) :
                        ?>
                        <tr>
                            <td><?php echo $this->escape($supplier["name"]); ?></td>

                            <td>
                                <a href="<?php echo $this->url(array('controller' => 'supplier', 'action' => 'select', 'id' => $supplier["id"])); ?>">consult</a>
                                <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "client:client", "inlitter")) { ?>

                                    <?php if ($supplier["in_litter"] == 0) { ?>
                                        <a href="<?php echo $this->url(array('controller' => 'supplier', 'action' => 'inlitter')); ?>">
                                            <img src="/styles/images/icons/icon_in_litter.png" alt="Inlitter" /></a>

                                    <?php } else { ?>
                                        <a href="<?php echo $this->url(array('controller' => 'supplier', 'action' => 'outlitter')); ?>">
                                            <img src="/styles/images/icons/icon_out_litter.png" alt="Oulitter" /></a>
                                    <?php } ?>
                                
                                <?php } ?>
                            </td>                      
                        </tr>
                    <?php
                    endforeach;
                }
                ?>
        </table>
        <div class="extrabottom">
<?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  
