          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Clients")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'client',
    'action' => 'add')); ?>">Add new client</a></p>
        <ul id="topbtns">
            	<li>
                	<a href="<?php echo $this->url(array('module' => 'client','controller' => 'role','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_calendar.png" alt="Role" /><br />role</a>
                </li>
                <li>
                        <a href="<?php echo $this->url(array('module' => 'client','controller' => 'client','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_user.png" alt="Clients" /><br />Clients</a>
                
                </li>
                <li>
                	<a href="<?php echo $this->url(array('module' => 'client','controller' => 'permission','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_create.png" alt="Permission" /><br />Permission  </a>
                </li>
               
                <li>
                	<a href="<?php echo $this->url(array('module' => 'client','controller' => 'resource','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_support.png" alt="Resource" /><br />Resource</a>
                </li>                
            </ul>
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>
                    
                </tr>
                                    
                <tr>
                    <th><?php echo $this->translate('Client name'); ?></th>
                    <th><?php echo $this->translate('Dated'); ?></th>
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('Status'); ?></th>
                    <th><?php echo $this->translate('Person_id?'); ?></th>
                    <th><?php echo $this->translate('Validation code'); ?></th>
                    <th><?php echo $this->translate('Phone'); ?></th>
                    <th><?php echo $this->translate('Role'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>
                    
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->paginator as $client) : ?>
                    <tr>
                        <td><?php echo $this->escape($client->name); ?></td>                         
                        <td><?php echo $this->escape($client->date); ?></td>
                        <td><?php echo $this->escape($client->email); ?></td>
                        <td><?php echo $this->escape($client->status); ?></td>
                        <td><?php echo $this->escape($client->person_id); ?></td>
                        <td><?php echo $this->escape($client->validation_code); ?></td>
                        <td><?php echo $this->escape($client->phone); ?></td>
                        <td><?php echo $this->escape($client->role); ?></td>               
                        <td>
                            <a href="<?php echo $this->url(array('controller' => 'client','action' => 'edit', 'id' => $client->id)); ?>">
                            	<img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'client','action' => 'delete', 'id' => $client->id)); ?>">
                            	<img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                        </td>                        
                    </tr>
                <?php endforeach; ?>
        </table>
       <div class="extrabottom">
            <?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  
