
<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Company")); ?></h1>
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>

                </tr>

                <tr>
                    <th><?php echo $this->translate('Company name'); ?></th>
                    <th><?php echo $this->translate('Fiscal name'); ?></th>
                    <th><?php echo $this->translate('Telephone'); ?></th>
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('City'); ?></th>
                    <th><?php echo $this->translate('Description'); ?></th>


                </tr>
            </thead>

            <tbody>

                <tr>
                    <td><?php echo $this->escape($this->select_company['name']); ?></td>                         
                    <td><?php echo $this->escape($this->select_company['fiscal_name']); ?></td>                         
                    <td><?php echo $this->escape($this->select_company['telephone']); ?></td>
                    <td><?php echo $this->escape($this->select_company['email']); ?></td>
                    <td><?php echo $this->escape($this->select_company['city']); ?></td>
                    <td><?php echo $this->escape($this->select_company['observation']); ?></td>
                </tr>

        </table>

    </div>

</div>

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Contacts Company : ") . $this->select_company['name']); ?></h1>

    </div>



    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>

                </tr>

                <tr>
                    <th><?php echo $this->translate('Contact name'); ?></th>
                    <th><?php echo $this->translate('Status'); ?></th>
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('telephone'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>
                    <th><?php echo $this->translate('Have User'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->paginator as $contact) : ?>
                    <tr id="rowcontact<?php echo $contact->id; ?>">
                        <td><?php echo $this->escape($contact["name"]); ?></td>                         
                        <td><?php echo $this->escape($contact["company"]); ?></td>                         
                        <td><?php echo $this->escape($contact["email"]); ?></td>
                        <td><?php echo $this->escape($contact["telephone"]); ?></td>
                        <td>
                            <a href="<?php echo $this->url(array('controller' => 'contact', 'action' => 'edit', 'id' => $contact["id"])); ?>">
                                <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'contact', 'action' => 'delete', 'id' => $contact["id"])); ?>">
                                <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'contact', 'action' => 'inlitter', 'id' => $contact["id"])); ?>">
                                <img src="/styles/images/icons/icon_in_litter.png" alt="Delete" /></a>
                        </td>
                        <td><?php if ($contact["acl_users_id"] == 0) {
                                ?>
                                SI
                            <?php } else { ?>
                                NO
                            <?php }?>
                        </td>    
                    </tr>

                <?php endforeach; ?>
        </table>
        <div class="extrabottom">
            <?php echo $this->paginator; ?>           
        </div>
    </div>
</div> 