<?php $acl = Login_Model_Acl::getInstance(); ?>
<div class="container">



    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Company")); ?></h1>
        <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "company:company", "add")) { ?>
            <p><a href="<?php  echo $this->url(array('controller' => 'company','action' => 'add'));
            ?>">Add Company</a></p>
       <?php } ?> 
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>

                </tr>

                <tr>
                    <th><?php echo $this->translate('Company name'); ?></th>
                    <th><?php echo $this->translate('Fiscal name'); ?></th>
                    <th><?php echo $this->translate('Telephone'); ?></th>
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('City'); ?></th>
                    <th><?php echo $this->translate('Description'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>

                <tr>
                    <td><?php echo $this->escape($this->select_company['name']); ?></td>                         
                    <td><?php echo $this->escape($this->select_company['fiscal_name']); ?></td>                         
                    <td><?php echo $this->escape($this->select_company['telephone']); ?></td>
                    <td><?php echo $this->escape($this->select_company['email']); ?></td>
                    <td><?php echo $this->escape($this->select_company['city']); ?></td>
                    <td><?php echo $this->escape($this->select_company['observation']); ?></td>
                    <td>

                        <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "company:company", "edit")) { ?>
                            <a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'edit', 'company_id' => $this->select_company['id'])); ?>">
                                <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                        <?php } ?>
                        <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "company:company", "delete")) { ?>

                            <a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'delete', 'company_id' => $this->select_company['id'])); ?>">
                                <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                        <?php } ?>
                        <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "company:company", "inlitter")) { ?>

                            <?php if ($this->select_company['in_litter'] == 0) { ?>
                                <a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'inlitter', 'id' => $this->select_company['id'])); ?>">
                                    <img src="/styles/images/icons/icon_in_litter.png" alt="Inlitter" /></a>

                            <?php } else { ?>
                                <a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'outlitter', 'id' => $this->select_company['id'])); ?>">
                                    <img src="/styles/images/icons/icon_in_litter.png" alt="Oulitter" /></a>
                            <?php } ?>
                        <?php } ?>
                    </td>        

                </tr>

        </table>

    </div>
</div>
    <!-- Table company end -->  
    <!-- Table contacts -->  


    <div class="container">
        <div class="conthead">
            <h1><?php echo $this->escape($this->translate("My Contacts")); ?></h1>
            <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "company:contact", "add")) { ?>
            <p><a href="<?php  echo $this->url(array('controller' => 'contact','action' => 'add'));
            ?>">Add Contact</a></p>
            <?php } ?> 

        </div>
        <div class="contentbox">
            <table width="100%">
                <thead>

                    <tr>
                        <th><?php echo $this->translate('Contact name'); ?></th>
                        <th><?php echo $this->translate('Company name'); ?></th>
                        <th><?php echo $this->translate('Email'); ?></th>
                        <th><?php echo $this->translate('telephone'); ?></th>
                        <th><?php echo $this->translate('direction'); ?></th>
                        <th><?php echo $this->translate('User'); ?></th>
                        <th><?php echo $this->translate('Actions'); ?></th>

                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($this->paginator_contact as $contact) : ?>
                        <tr>
                            <td><?php echo $this->escape($contact["name"]); ?></td>                         
                            <td><?php echo $this->escape($contact["company"]); ?></td>                         
                            <td><?php echo $this->escape($contact["email"]); ?></td>
                            <td><?php echo $this->escape($contact["telephone"]); ?></td>
                            <td><?php echo $this->escape($contact["direction"]); ?></td>
                            <td><?php if ($contact["acl_users_id"] == 0) { ?>
                                    NO tiene usuario
                                <?php } else { ?>
                                    tiene usuario
                                <?php } ?>
                            </td>
                            <td>
                                <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "company:contact", "edit")) { ?>
                                    <a href="<?php echo $this->url(array('controller' => 'contact', 'action' => 'edit', 'id' => $contact["id"])); ?>">
                                        <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                                <?php } ?>

                                <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "company:company", "inlitter")) { ?>

                                    <a href="<?php echo $this->url(array('controller' => 'contact', 'action' => 'inlitter', 'id' => $contact["id"])); ?>">
                                        <img src="/styles/images/icons/icon_in_litter.png" alt="Delete" /></a>
                                <?php } ?>
                                <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "company:company", "delete")) { ?>
                                    <a href="<?php echo $this->url(array('controller' => 'contact', 'action' => 'delete', 'id' => $contact["id"])); ?>">
                                        <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                                <?php } ?> 
                           
                            </td>                        
                        </tr>
                    <?php endforeach; ?>
            </table>
            <div class="extrabottom">
                <?php echo $this->paginator_contact; ?>           
            </div>
        </div>
    </div>
    <!-- Table styles end -->  

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Companies Client")); ?></h1>
        <p><a href="<?php
                echo $this->url(array('controller' => 'company',
                    'action' => 'add'));
                ?>">Add Client</a></p>

    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>

                </tr>

                <tr>
                    <th><?php echo $this->translate('Company name'); ?></th>
                    <th><?php echo $this->translate('Fiscal name'); ?></th>
                    <th><?php echo $this->translate('Type'); ?></th>
                    <th><?php echo $this->translate('Telephone'); ?></th>
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('City'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php
                if ($this->paginator) {
                    foreach ($this->paginator as $company) :
                        ?>
                        <tr>
                            <td><?php echo $this->escape($company['name']); ?></td>                         
                            <td><?php echo $this->escape($company['fiscal_name']); ?></td>                         
                            <td><?php echo $this->escape($company['company_types_name']); ?></td>
                            <td><?php echo $this->escape($company['telephone']); ?></td>
                            <td><?php echo $this->escape($company['email']); ?></td>
                            <td><?php echo $this->escape($company['city']); ?></td>

                            <td>
                                <?php if ($company['in_litter'] == 0) { ?>
                                    <a href="<?php echo $this->url(array('module' => 'production', 'controller' => 'production', 'action' => 'add', 'company_id' => $company['id'])); ?>">
                                        <img src="/styles/images/icons/icon_claketa.png" alt="Añadir production" /></a>

                                <?php } ?>
                                <a href="<?php echo $this->url(array('controller' => 'contact', 'action' => 'index', 'company_id' => $company['id'])); ?>">
                                    <img src="/styles/images/icons/icon_user.png" alt="Consultar contactos" /></a>
                                <a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'edit', 'company_id' => $company['id'])); ?>">
                                    <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                                <a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'delete', 'company_id' => $company['id'])); ?>">
                                    <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                                <?php if ($company['in_litter'] == 0) { ?>
                                    <a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'inlitter', 'id' => $company['id'])); ?>">
                                        <img src="/styles/images/icons/icon_in_litter.png" alt="Inlitter" /></a>

                                <?php } else { ?>
                                    <a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'outlitter', 'id' => $company['id'])); ?>">
                                        <img src="/styles/images/icons/icon_in_litter.png" alt="Oulitter" /></a>
                                <?php } ?>

                            </td>                        
                        </tr>
                    <?php
                    endforeach;
                }
                ?>
        </table>
        <div class="extrabottom">
<?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Permissionproductions")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'permissionproduction',
    'action' => 'add'));
?>">Add new permissionproduction</a></p>

    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
         
                <tr>
                    <th><?php echo $this->translate('Name'); ?></th>
                                 
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php if ($this->paginator_user_company) {
                    foreach ($this->paginator_user_company as $user_company) :
                     
                        if ($user_company["acl_users_id"]!=$_SESSION["gpms"]["storage"]->id) {
                        ?>
                        <tr>
                            <td><?php echo $this->escape($user_company["name"]); ?></td> 
                            <td><?php echo $this->escape($user_company["email"]); ?></td> 
                            
                            <td>
                                <a href="<?php echo $this->url(array('controller' => 'permissionproduction', 'action' => 'edit', 'id' => $user_company["id"])); ?>">
                                    <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                                <a href="<?php echo $this->url(array('controller' => 'permissionproduction', 'action' => 'delete', 'id' =>  $user_company["id"])); ?>">
                                    <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                            </td>                        
                        </tr>
                <?php }
                endforeach;
            } ?>
        </table>
        <div class="extrabottom">
<?php echo $this->paginator_user_company; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  
