 

<!-- Charts box start -->          
<div class="container half " id="graphs">
    <div class="conthead">

        <h2 class="left">Client</h2>
        <ul class="tabhead">
   
             <li><a href="#tabs-1">New production</a></li>
                     
            <li><a href="#tabs-2">New Client</a></li>
        </ul>
    </div>
    <!-- Tabbed navigation start -->                    
    <div class="contentbox">
        <!-- Tabbed boxes end -->  

        <div id="tabs-1">
            <?php
                echo $this->production_form;
            ?>
        </div>
        <div id="tabs-2">
            <?php
              echo $this->company_form;              
            ?>
       


    </div>
</div>

<link rel="stylesheet" type="text/css" media="all" href="/styles/css/calendar/skins/tiger/theme.css" title="Tiger" /> 
<script type="text/javascript">
    Calendar.setup({
        inputField     :    "f_date_end",      // id of the input field
        ifFormat       :    "%Y-%m-%d %H:%M:00",       // format of the input field
        showsTime      :    true,            // will display a time selector
        singleClick    :    false,           // double-click mode
        timeFormat     :    "24",
        step           :    1                // show all years in drop-down boxes (instead of every other year as default)
    });
    
     Calendar.setup({
        inputField     :    "f_date_start",      // id of the input field
        ifFormat       :    "%Y-%m-%d %H:%M:00",       // format of the input field
        showsTime      :    true,            // will display a time selector
        singleClick    :    false,           // double-click mode
        timeFormat     :    "24",
        step           :    1                // show all years in drop-down boxes (instead of every other year as default)
    });
</script>                                                                                            <!--
  