 

<!-- Charts box start -->          
<div class="container half " id="graphs">
    <div class="conthead">

        <h2 class="left">Client</h2>
        <ul class="tabhead">
   
             <li><a href="#tabs-1">New production</a></li>
                     
            <li><a href="#tabs-2">New Client</a></li>
        </ul>
    </div>
    <!-- Tabbed navigation start -->                    
    <div class="contentbox">
        <!-- Tabbed boxes end -->  

        <div id="tabs-1">
            <?php
                echo $this->production_form;
            ?>
        </div>
        <div id="tabs-2">
            <?php
              echo $this->company_form;              
            ?>
        </div>
        <?php
 
$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.8.23/themes/smoothness/jquery-ui.css', 'screen');
$this->headScript()->appendFile('/js/jquery-ui-sliderAccess.js');
$this->headScript()->appendFile('/js/jquery-ui-timepicker-addon.js');
$this->headScript()->appendScript('
    $(function() {
        $("#start_time").datetimepicker({showSecond: true, dateFormat: "yy-mm-dd", timeFormat: "hh:mm:ss"});
        $("#end_time").datetimepicker({showSecond: true, dateFormat: "yy-mm-dd", timeFormat: "hh:mm:ss"});
    });
');
        ?>


    </div>
</div>

 