<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Consult Production")); ?></h1> 
         <a href="<?php echo $this->url(array('controller' => 'permissionproduction', 'action' => 'index')); ?>"> user production   </a>
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>

                <tr>
                    <th><?php echo $this->translate('Production name'); ?></th>
                    <th><?php echo $this->translate('Client company name'); ?></th>
                    <th><?php echo $this->translate('Production type'); ?></th>
                    <th><?php echo $this->translate('Own Company name'); ?></th>
                    <th><?php echo $this->translate('Date Start'); ?></th>
                    <th><?php echo $this->translate('Date End'); ?></th>
                    <th><?php echo $this->translate('Ovservation'); ?></th>
                    <th><?php echo $this->translate('Budget'); ?></th>
                    <th><?php echo $this->translate('Status'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>
                </tr>
            </thead>

            <tbody>
                
                <tr>
                    <td><?php echo $this->escape($this->production->name); ?></td>
                    <td><?php echo $this->escape($this->production->client_company_name); ?></td> 
                    <td><?php echo $this->escape($this->production->production_type_name); ?></td>
                    <td><?php echo $this->escape($this->production->own_company_name); ?></td>                        
                    <td><?php echo $this->escape($this->production->date_start); ?></td>
                    <td><?php echo $this->escape($this->production->date_end); ?></td>
                    <td><?php echo $this->escape($this->production->observation); ?></td>
                    <td><?php echo $this->escape($this->production->budget); ?></td>
                    <td><?php echo $this->escape($this->production->status); ?></td>


                    <td>
                        <a href="<?php echo $this->url(array('controller' => 'activity', 'action' => 'index')); ?>">Activitis production</a>
                        <a href="<?php echo $this->url(array('controller' => 'production', 'action' => 'edit')); ?>"><img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                        <a href="<?php echo $this->url(array('controller' => 'production', 'action' => 'delete')); ?>"><img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>               
                    </td>                        
                </tr>

        </table>

    </div>
    <?php Zend_Debug::dump($_SESSION); ?>
   
</div>