<?php $acl = Login_Model_Acl::getInstance(); ?>
<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Consult Production")); ?></h1>
        <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:permissionproduction", "add")) { ?>
            <a href="<?php echo $this->url(array('controller' => 'permissionproduction', 'action' => 'index')); ?>"> user production   </a>
        <?php } ?>
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>

                <tr>
                    <th><?php echo $this->translate('Production name'); ?></th>
                    <th><?php echo $this->translate('Company name'); ?></th>
                    <th><?php echo $this->translate('Client company name'); ?></th>
                    <th><?php echo $this->translate('Production type'); ?></th>
                    <th><?php echo $this->translate('Date Start'); ?></th>
                    <th><?php echo $this->translate('Date End'); ?></th>
                    <th><?php echo $this->translate('Ovservation'); ?></th>
                    <th><?php echo $this->translate('Direction'); ?></th>
                    <th><?php echo $this->translate('Status'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>
                </tr>
            </thead>

            <tbody>

                <tr>
                    <td><?php echo $this->escape($this->production["name"]); ?></td>
                    <td><?php echo $this->escape($this->production["own_company_name"]); ?></td> 
                    <td><?php echo $this->escape($this->production["client_company_name"]); ?></td> 
                    <td><?php echo $this->escape($this->production["production_type_name"]); ?></td>
                    <td><?php echo $this->escape($this->production["date_start"]); ?></td>
                    <td><?php echo $this->escape($this->production["date_end"]); ?></td>
                    <td><?php echo $this->escape($this->production["observation"]); ?></td>
                    <td><?php echo $this->escape($this->production["direction"]); ?></td>
                    <td><?php echo $this->escape($this->production["status"]); ?></td>

                    <td>
                         <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:production", "edit")) { ?>
                        <a href="<?php echo $this->url(array('controller' => 'production', 'action' => 'edit')); ?>"><img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                         <?php } ?>
                         <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:production", "delete")) { ?>
                        <a href="<?php echo $this->url(array('controller' => 'production', 'action' => 'delete')); ?>"><img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>               
                         <?php } ?>
                    </td>

                </tr>



        </table>

    </div>
</div>


<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Activitys")); ?></h1>
        <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:activity", "add")) { ?>
            <p><a href="<?php
            echo $this->url(array('controller' => 'activity',
            'action' => 'add'));
            ?>">Add new activity</a></p>
        <?php } ?>
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>

                <tr>
                    <th><?php echo $this->translate('Name'); ?></th>
                    <th><?php echo $this->translate('Activity_types'); ?></th>
                    <th><?php echo $this->translate('Client_resp_name'); ?></th>
                    <th><?php echo $this->translate('own_resp_name'); ?></th>
                    <th><?php echo $this->translate('Date_start'); ?></th>
                    <th><?php echo $this->translate('Date_end'); ?></th>
                    <th><?php echo $this->translate('Type'); ?></th> 
                    <th><?php echo $this->translate('Status'); ?></th>
                </tr>
            </thead>

            <tbody>
                <?php
                if ($this->paginator) {
                    foreach ($this->paginator as $activity) :
                        ?>
                        <tr>
                            <td><?php echo $this->escape($activity["name"]); ?></td>
                            <td><?php echo $this->escape($activity["activity_type_name"]); ?></td>
                            <td><?php echo $this->escape($activity["contact_client_company_name"]); ?></td>
                            <td><?php echo $this->escape($activity["contact_own_company_name"]); ?></td>
                            <td><?php echo $this->escape($activity["date_start"]); ?></td>
                            <td><?php echo $this->escape($activity["date_end"]); ?></td>
                            <td><?php echo $this->escape($activity["status"]); ?></td>
                            <td>
                                 <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:activity", "select")) { ?>
                                <a href="<?php echo $this->url(array('controller' => 'activity', 'action' => 'select', 'id' => $activity["id"])); ?>">
                                    Select</a>
                                 <?php } ?>
                                 <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:activity", "delete")) { ?>
                                <a href="<?php echo $this->url(array('controller' => 'activity', 'action' => 'delete', 'id' => $activity["id"])); ?>">
                                    <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                                 <?php } ?>
                            </td>                        
                        </tr>
                        <?php
                    endforeach;
                }
                ?>
        </table>
        <div class="extrabottom">
            <?php echo $this->paginator; ?>           
        </div>
    </div>

</div>
<!-- Table styles end -->  

<?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:permissionproduction", "index")) { ?>  
<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Permission of the production")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'permissionproduction',
    'action' => 'add'));
?>">Add new permissionproduction</a></p>

    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
         
                <tr>
                    <th><?php echo $this->translate('Name'); ?></th>
                    <th><?php echo $this->translate('Production Role'); ?></th>              
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php if ($this->paginator2) {
                    foreach ($this->paginator2 as $permissionproduction) :
                     
                        if ($permissionproduction["acl_users_id"]!=$_SESSION["gpms"]["storage"]->id) {
                        ?>
                        <tr>
                            <td><?php echo $this->escape($permissionproduction["production_user_name"]); ?></td> 
                            <td><?php echo $this->escape($permissionproduction["production_role_name"]); ?></td> 
                            <td><?php echo $this->escape($permissionproduction["email"]); ?></td> 
                            <td>
                                <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:permissionproduction", "edit")) { ?>  
                                <a href="<?php echo $this->url(array('controller' => 'permissionproduction', 'action' => 'edit', 'id' => $permissionproduction["id"])); ?>">
                                    <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                                <?php } ?>
                                <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:permissionproduction", "delete")) { ?>  
                                <a href="<?php echo $this->url(array('controller' => 'permissionproduction', 'action' => 'delete', 'id' =>  $permissionproduction["id"])); ?>">
                                    <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                                 <?php } ?>
                            </td>                        
                        </tr>
                <?php }
                endforeach;
            } ?>
        </table>
        <div class="extrabottom">
<?php echo $this->paginator2; ?>           
        </div>
    </div>
</div>
 <?php } ?>
<!-- Table permission end -->  

