<div class="container">
    <div class="conthead">
        <h2>Production</h2>
    </div>
    <div class="contentbox">
        
    <?php
        
        echo $this->form;
        ?>
        
    </div>
         
             

    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Activities")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'activity','action' => 'add')); ?>">Add new Activity</a></p>
        <ul id="topbtns">
            
            </ul>
    </div>
    <div class="contentbox">
      <table width="100%">
            <thead>
                <tr>
                    
                </tr>
                                    
                <tr>
                    <th><?php echo $this->translate('Responsible'); ?></th>
                    <th><?php echo $this->translate('Client'); ?></th>
                    <th><?php echo $this->translate('Client responsible name'); ?></th>
                    <th><?php echo $this->translate('Type'); ?></th>
                    <th><?php echo $this->translate('Date_start'); ?></th>
                    <th><?php echo $this->translate('Status'); ?></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->paginator as $activity) : ?>
                    <tr>
                        <td><?php echo $this->escape($activity->responsible); ?></td>
                        <td><?php echo $this->escape($activity->company_name); ?></td>
                        <td><?php echo $this->escape($activity->client_name); ?></td>
                        <td><?php echo $this->escape($activity->activity_types); ?></td>
                        <td><?php echo $this->escape($activity->date_start); ?></td>
                        <td><?php echo $this->escape($activity->status); ?></td>
                        <td>
                            
                            <a href="<?php echo $this->url(array('controller' => 'activity','action' => 'edit', 'id' => $activity->id)); ?>">
                            	<img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'activity','action' => 'delete', 'id' => $activity->id)); ?>">
                            	<img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                        </td>                        
                    </tr>
                <?php endforeach; ?>
        </table>
       <div class="extrabottom">
            <?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
