<?php $acl = Login_Model_Acl::getInstance(); ?>
<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Productions")); ?></h1>
        <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:production", "add")) { ?>
            <p><a href="<?php
            echo $this->url(array('controller' => 'production',
            'action' => 'add'));
            ?>">Add new production</a></p>
            <?php } ?> 
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>

                <tr>
                    <th><?php echo $this->translate('Production name'); ?></th>
                    <th><?php echo $this->translate('Company name'); ?></th>
                    <th><?php echo $this->translate('Client company name'); ?></th>
                    <th><?php echo $this->translate('Production type'); ?></th>
                    <th><?php echo $this->translate('Date Start'); ?></th>
                    <th><?php echo $this->translate('Date End'); ?></th>
                    <th><?php echo $this->translate('Ovservation'); ?></th>
                    <th><?php echo $this->translate('Budget'); ?></th>
                    <th><?php echo $this->translate('Status'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>
                </tr>
            </thead>

            <tbody>
                <?php
                if ($this->paginator) {
                    foreach ($this->paginator as $production) :
                        ?>
                        <tr>
                            <td><?php echo $this->escape($production["name"]); ?></td>
                             <td><?php echo $this->escape($production["own_company_name"]); ?></td> 
                            <td><?php echo $this->escape($production["client_company_name"]); ?></td> 
                            <td><?php echo $this->escape($production["production_type_name"]); ?></td>
                            <td><?php echo $this->escape($production["date_start"]); ?></td>
                            <td><?php echo $this->escape($production["date_end"]); ?></td>
                            <td><?php echo $this->escape($production["observation"]); ?></td>
                            <td><?php echo $this->escape($production["budget"]); ?></td>
                            <td><?php echo $this->escape($production["status"]); ?></td>


                            <td>
                                <a href="<?php echo $this->url(array('controller' => 'production', 'action' => 'select', 'id' => $production->id)); ?>">Consult</a>

                            </td>                        
                        </tr>
                    <?php endforeach;
                }
                ?>
        </table>
        <div class="extrabottom">
<?php echo $this->paginator; ?>           
        </div>

        <!-- Table styles end -->  
