<?php $acl = Login_Model_Acl::getInstance(); ?>          
<div class="container sml Left">
    <div class="conthead">
        <h2>Menu Administration</h2>
    </div>
    <div class="contentbox">
        <ul class="summarystats">
            <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "user:user", "index")) { ?>  

                <li>
                    <p class="statcount">Users</p>   <p class="statview"> <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'select')); ?>"> Consult</a></p>

                </li>
            <?php } ?>
            <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "user:role", "index")) { ?>  

                <li>
                    <p class="statcount">Roles</p>   <p class="statview"> <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'role' )); ?>"> Consult</a></p>

                </li>
            <?php } ?>
            <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "user:permission", "index")) { ?>  

                <li>
                    <p class="statcount">Permissions</p>   <p class="statview"> <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'permission')); ?>"> Consult</a></p>

                </li>
            <?php } ?>
            <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "user:resource", "index")) { ?>  

                <li>
                    <p class="statcount">Resources</p>   <p class="statview"> <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'resource' )); ?>"> Consult</a></p>
                </li>
            <?php } ?>
        </ul>

    </div>
</div>