
<ul class="pagination" >
    <?php if (isset($this->previous)): ?>
        <li class="text"><a href="<?= $this->url(array('page' => $this->first)); ?>"><?= $this->translate("Start"); ?></a> </li>

        <li class="text"><a href="<?= $this->url(array('page' => $this->previous)); ?>"><?= $this->translate("Previous"); ?></a> </li>
    <?php endif; ?>
    <!-- Numbered page links -->

    <?php if (!isset($this->pagesInRange[1])): ?>
        <li>[...]</li>
    <?php endif; ?>

    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li><a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a></li>
        <?php else: ?>
            <li class="page"><a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php if ($this->last > $page): ?>
        <li>[...]</li>
    <?php endif; ?>                                                                        
    <?php if (isset($this->next)): ?>
        <li class="text"><a href="<?= $this->url(array('page' => $this->next)); ?>"><?= $this->translate("Next"); ?></a> </li>
        <li class="text"><a href="<?= $this->url(array('page' => $this->last)); ?>"><?= $this->translate("End"); ?></a> </li>
    <?php endif; ?>
</ul>