<ul id="nav">
    <?php
    //die();
    $acl = Login_Model_Acl::getInstance();
    $list = $acl->listResourceByUser();
//Zend_Debug::dump($this->container,"container");
//    Zend_Debug::dump($list, "lust");



    $html = array();


    foreach ($this->container as $page) {

        if (isset($list['allowed'][$page->resource . ' - ' . $page->privilege])) {
            $permission = $list['allowed'][$page->resource . ' - ' . $page->privilege];
        } else {
            $permission = "denied";
        }
        if ($permission == 'allowed') {
            $html[] = "<li>";
            $html[] = "<a class='collapsed heading' \">";
            $html[] = $page->getLabel();
            $html[] = "</a>";
            if (!empty($page->pages)) {
                $html[] = "<ul class='navigation'>";
                foreach ($page->pages as $subpage) {
                    //echo $subpage->action;
                    if (isset($list['allowed'][$subpage->resource . ' - ' . $subpage->privilege])) {
                        $permission_sub = $list['allowed'][$subpage->resource . ' - ' . $subpage->privilege];
                        
                        if ($subpage->resource . ' - ' . $subpage->privilege == "production:production - consult") {
                            
                            if (!isset($_SESSION["production"]["id"])) {
                                $permission_sub = "denied";
                            }
                        }
                    } else {
                        $permission_sub = "denied";
                    }
//                  
                    if ($permission_sub == 'allowed') {
                        $html[] = "<li>";
                        if ($href = $subpage->getHref())
                            $html[] = "<a href=\"{$href}\">";
                        else
                            $html[] = "<span>";
                        // $html[] = "<img src=\"/ui/cms/img/icons/edit.png\" alt=\"\"/>";
                        $html[] = $subpage->getLabel();
                        if ($href)
                            $html[] = "</a>";
                        else
                            $html[] = "</span>";
                        $html[] = "</li>";
                    }
                }
                $html[] = "</ul>";
            }

            $html[] = "</li>";
        }
    }

    echo join(PHP_EOL, $html);
    ?>
</ul>