<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
echo $this->doctype();
?>
<head>

    <?php echo $this->headMeta(); ?>
    <?= $this->headTitle($this->escape($this->title)) ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css'); ?>
    <!-- Calendar Styles -->
    <link href="/styles/css/fullcalendar.css" rel="stylesheet" type="text/css" />
    <!-- Fancybox/Lightbox Effect -->
    <link href="/styles/css/jquery.fancybox-1.3.4.css" rel="stylesheet" type="text/css" />
    <!-- WYSIWYG Editor -->
    <link href="/styles/css/wysiwyg.css" rel="stylesheet" type="text/css" />
    <!-- Main Controlling Styles -->
    <link href="/styles/css/main.css" rel="stylesheet" type="text/css" />
    <!-- Blue Theme Styles -->
    <link href="/styles/themes/blue/styles.css" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/ajax_functions.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/onclick/onclick.js" ></script>  
    <?php
    if ($this->dojo()->isEnabled()) {
        
        $this->dojo()->setDjConfigOption('isDebug', false)
                //     ->setLocalPath(DOJO_PATH)
                ;  
        echo $this->dojo();
    }
    ?>
</head>

<body>
    <?php $acl = Login_Model_Acl::getInstance(); ?>
    <!-- Top header/black bar start -->
    <div id="header">
        <img src="/styles/images/logo.png" alt="GlobalPMS" class="logo" />
     


    </div>

    <!-- Top header/black bar end -->   

    <!-- Left side bar start -->
    <div id="left">
        <!-- Left side bar start -->

        <!-- Toolbox dropdown start -->
        <div id="openCloseIdentifier"></div>
      
        <!-- Toolbox dropdown end -->   

        <!-- Userbox/logged in start -->
        <div id="userbox">
            <p>Welcome <?php
    //TODO hacer 
    echo $_SESSION["gpms"]["storage"]->name;
    ?></p>
            <p><span>LOGGED : <?php echo $_SESSION["gpms"]["role"] ?> </span></p>
            <p><span>PRODUCTION: <?php echo $_SESSION["production"]["name"]; ?></span></p>  
            <p><span>ACTIVITY: <?php echo $_SESSION["production"]["activity_name"]; ?></span></p>
            <ul>
               <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'edit', 'id' => $_SESSION["gpms"]["storage"]->id)); ?>" title="Configure"><img src="/styles/images/icons/icon_cog.png" alt="Configure" /></a></li>
               <li><a href="<?php echo $this->url(array('module' => 'login', 'controller' => 'index', 'action' => 'logout')); ?>" title="Logout"><img src="/styles/images/icons/icon_unlock.png" alt="Logout" /></a></li>
            </ul> 
        </div>
        <!-- Userbox/logged in end -->  

        <!-- Main navigation start -->         
        <ul id="nav">

        </ul>
    </div>      
    <!-- Main navigation end --> 

    <!-- Left side bar start end -->   

    <!-- Right side start -->     
    <div id="right">

        <!-- Breadcrumb start -->  
         
        <!-- Breadcrumb end -->  

        <!-- Top/large buttons start -->  
        <ul id="topbtns">
            <li class="desc"><strong>Quick Links</strong><br />Popular shortcuts</li>
            <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "controlmodule:controlmodule", "index"))  { ?>  
            <li>
                <a href="<?php echo $this->url(array('module' => 'controlmodule', 'controller' => 'controlmodule', 'action' => 'select')); ?>"><img src="/styles/images/icons/icon_lrg_media.png" alt="control de modulos" /><br />modulos</a>
            </li>
             <?php } ?>
              <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "user:user", "index")) { ?>  
            
            <li>
                <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'select')); ?>"><img src="/styles/images/icons/icon_lrg_user.png" alt="Users" /><br />Users</a>

            </li>
            <?php } ?> 
            <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "company:company", "index") and isset($_SESSION["company"]["id"])) { ?>  
  
            <li>
                <a href="<?php echo $this->url(array('module' => 'company', 'controller' => 'company', 'action' => 'select')); ?>"><img src="/styles/images/icons/icon_company.png" alt="Companies" /><br />Companies</a>

            </li>
            <?php } ?> 
             <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "company:company", "index")and isset($_SESSION["company"]["id"])) { ?> 
          
            <li>
                <a href="<?php echo $this->url(array('module' => 'production', 'controller' => 'production', 'action' => 'index')); ?>"><img src="/styles/images/icons/icon_claketa.png" alt="Production" /><br />Production</a>

            </li>
            <?php } ?> 
            <!--
            <li>
                <a href="<?php echo $this->url(array('module' => 'finances', 'controller' => 'finances', 'action' => 'index')); ?>"><img src="/styles/images/icons/icon_finances.png" alt="Finances" /><br />Finances</a>

            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'managementtype', 'controller' => 'managementtype', 'action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_support.png" alt="Production" /><br />Types Configure</a>

            </li> 
            -->
            <li>
                LANGUAGE
               <?php
               
                include_once(APPLICATION_PATH . '/modules/default/forms/Languages.php');
                $form = new Default_Form_Languages();
                echo $form;
                ?>
            </li>
             <li> 
                COMPANIES : 
                <?php
                include_once(APPLICATION_PATH . '/modules/default/forms/companies.php');
                $form = new Default_Form_Companies();
                echo $form;
                ?>
            </li>
           
        </ul>
        <!-- Top/large buttons end -->  

        <!-- Main content start -->      

        <div id="content">

<?php echo $this->layout()->content; ?> 
        </div>

        <!-- Footer start --> 
        <p id="footer">&copy; openhost.com</p>
        <!-- Footer end -->      

    </div>
    <!-- Right side end --> 
<?php /*
    <script type="text/javascript" src="http://dwpe.googlecode.com/svn/trunk/_shared/EnhanceJS/enhance.js"></script>	
    <script type='text/javascript' src='http://dwpe.googlecode.com/svn/trunk/charting/js/excanvas.js'></script>
    <script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js'></script>
    <script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js'></script>
    <script type='text/javascript' src='js/jquery.fancybox-1.3.4.pack.js'></script>
    <script type='application/javascript' src='js/fullcalendar.min.js'></script>
    <script type='text/javascript' src='js/jquery.wysiwyg.js'></script>
    <script type='text/javascript' src='js/visualize.jQuery.js'></script>
    <script type='application/javascript' src='js/functions.js'></script>
*/?>
  </body>
 </html>

