<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
echo $this->doctype();
?>
<head>

    <?php echo $this->headMeta(); ?>
    <?= $this->headTitle($this->escape($this->title)) ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css');
    ?>

    <!-- Calendar Styles -->
    <link href="/styles/css/fullcalendar.css" rel="stylesheet" type="text/css" />
    <!-- Fancybox/Lightbox Effect -->
    <link href="/styles/css/jquery.fancybox-1.3.4.css" rel="stylesheet" type="text/css" />
    <!-- WYSIWYG Editor -->
    <link href="/styles/css/wysiwyg.css" rel="stylesheet" type="text/css" />
    <!-- Main Controlling Styles -->
    <link href="/styles/css/main.css" rel="stylesheet" type="text/css" />
    <!-- Blue Theme Styles -->
    <link href="/styles/themes/grey/styles.css" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/ajax_functions.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/onclick/onclick.js" ></script>  
    <?php
    if ($this->dojo()->isEnabled()) {

        $this->dojo()->setDjConfigOption('isDebug', false)
        //     ->setLocalPath(DOJO_PATH)
        ;
        echo $this->dojo();
    }
    ?>
</head>

<body>
    <?php $acl = Login_Model_Acl::getInstance(); ?>
    <!-- Top header/black bar start -->
    <div id="header">
        <img src="/styles/images/logo.png" alt="AdminCP" class="logo" />
<!--        <div id="searchbox">
            <input type="text" class="searchinput" />
            <input type="image" src="/styles/images/search_btn.png" class="searchbtn" />
        </div>-->


    </div>

    <!-- Top header/black bar end -->   

    <!-- Left side bar start -->
    <div id="left">
        <!-- Left side bar start -->

        <!-- Toolbox dropdown start -->
        <div id="openCloseIdentifier"></div>
        <!--        <div id="slider">
                    <ul id="sliderContent">
                        <li><a href="#" title="">Change Username</a></li>
                        <li class="alt"><a href="#" title="">Change Password</a></li>
                        <li><a href="#" title="">Change Address</a></li>
                        <li class="alt"><a href="#" title="">Payment Details</a></li>
                        <li><a href="#" title="">Log Out</a></li>
                    </ul>
                    <div id="openCloseWrap">
                        <div id="toolbox">
                            <a href="#" title="Toolbox Dropdown" class="toolboxdrop">Toolbox <img src="/styles/images/icon_expand_grey.png" alt="Expand" /></a>
                        </div>
                    </div>
                </div>-->
        <!-- Toolbox dropdown end -->   

        <!-- Userbox/logged in start -->
        <div id="userbox">
            <p>Welcome <?php echo $_SESSION["gpms"]["storage"]->name; ?></p>
            <p><span>LOGGED : <?php echo $_SESSION["gpms"]["role"] ?> </span></p>
<!--            <p><span>PRODUCTION: <?php echo $_SESSION["production"]["name"]; ?></span></p>  -->
<!--            <p><span>ACTIVITY: <?php echo $_SESSION["production"]["activity_name"]; ?></span></p>-->
            <ul>
                <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'user', 'action' => 'editownuser')); ?>" title="Configure"><img src="/styles/images/icons/icon_cog.png" alt="Configure" /></a></li>
                <li><a href="<?php echo $this->url(array('module' => 'login', 'controller' => 'index', 'action' => 'logout')); ?>" title="Logout"><img src="/styles/images/icons/icon_unlock.png" alt="Logout" /></a></li>
            </ul> 
        </div>

        <?php
        if (isset($_SESSION["company"]["id"])) {
            $list = $acl->listResourceByUser();
//                Zend_Debug::dump($list);
            echo $this->navigation()
                    ->menu()
                    ->setPartial(array('_element_menu.phtml', 'default'))
                    ->setMaxDepth(1)
                    ->setTranslator(Zend_Registry::get('Zend_Translate'))
                    ->setUlClass('navigation')
                    ->setOnlyActiveBranch(false)
                    ->setAcl($acl)
                    ->setRole($list['role']);
        }
        ?>
    </div>
    <!-- Main navigation end -->



    <!-- Left side bar start end -->   

    <!-- Right side start -->     
    <div id="right">

        <!-- Breadcrumb start -->  
        <div id="breadcrumb">
            <ul>            
                <li><img src="/styles/images/icon_breadcrumb.png" alt="Location" /></li>

                <li>
                    <?php 
                    $list = $acl->listResourceByUser();
                    echo $this->navigation()
                            ->breadcrumbs()
                            ->setMinDepth(0)
                            ->setLinkLast(false)
                            ->setSeparator(" / ")
                            ->setAcl($acl)
                            ->setRole($list['role'])
                    //->render()
                    ;
                    ?>
                </li>
            </ul>
        </div>
        <!-- Breadcrumb end -->  

        <!-- Top/large buttons start -->  
        <ul id="topbtns">
            <li class="desc"><strong>Quick Links</strong><br />Popular shortcuts</li>
            
            <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "user:index", "index")) { ?>  

                <li>
                    <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'index', 'action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_user.png" alt="Users" /><br />Admin</a>

                </li>
            <?php } ?>
            
            <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "company:index", "index") and isset($_SESSION["company"]["id"])) { ?>  

                <li>
                    <a href="<?php echo $this->url(array('module' => 'company', 'controller' => 'index', 'action' => 'index')); ?>"><img src="/styles/images/icons/icon_company.png" alt="Companies" /><br />Companies</a>

                </li>
            <?php } ?> 
            <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:production", "index") and isset($_SESSION["company"]["id"])) { ?>       
                <li>
                    <a href="<?php echo $this->url(array('module' => 'production', 'controller' => 'production', 'action' => 'index')); ?>"><img src="/styles/images/icons/icon_claketa.png" alt="Production" /><br />Production</a>

                </li>
            <?php } ?> 
 

            <!--            <li>
                            LANGUAGE
            <?php
            include_once(APPLICATION_PATH . '/modules/default/forms/Languages.php');
            $form = new Default_Form_Languages();
            echo $form;
            ?>
                        </li>-->
            <li> 
                COMPANIES : 
                <?php
                include_once(APPLICATION_PATH . '/modules/default/forms/companies.php');
                $form = new Default_Form_Companies();
                echo $form;
                ?>
            </li>

        </ul>
        <!-- Top/large buttons end -->  

        <!-- Main content start -->      

        <div id="content">

            <?php echo $this->layout()->content; ?> 
        </div>

        <!-- Footer start --> 
        <p id="footer">&copy; openhost.com</p>
        <!-- Footer end -->      

    </div>
    <!-- Right side end --> 

    <script type="text/javascript" src="http://dwpe.googlecode.com/svn/trunk/_shared/EnhanceJS/enhance.js"></script>
    <script type='text/javascript' src='http://dwpe.googlecode.com/svn/trunk/charting/js/excanvas.js'></script>
    <script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js'></script>
    <script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl(); ?>/js/jquery.fancybox-1.3.4.pack.js'></script>
    <script type='application/javascript' src='<?php echo $this->baseUrl(); ?>/js/fullcalendar.min.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl(); ?>/js/jquery.wysiwyg.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl(); ?>/js/visualize.jQuery.js'></script>

    <script type='application/javascript' src='<?php echo $this->baseUrl(); ?>/js/functions.js'></script>

</body>
</html>

