<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>CP Login</title>
<link href="/styles/css/login.css" rel="stylesheet" type="text/css" />
</head>
<body>
	<div id="logincontainer">
    	<h1>CP<span>access</span></h1>
        
        <div id="loginbox">
            <?php echo $this->layout()->content; ?> 
            <p><a href="#">Forgotten password</a></p>      
        </div>
    </div>
</body>
</html>
