          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Clients")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'client',
    'action' => 'add'));
?>">Add new client</a></p>

    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
         
                <tr>
                    <th><?php echo $this->translate('name'); ?></th>

                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php if ($this->paginator) {
                    foreach ($this->paginator as $client) :
                        ?>
                        <tr>
                            <td><?php echo $this->escape($client["name"]); ?></td>                         
                            <td>
                                <a href="<?php echo $this->url(array('controller' => 'client', 'action' => 'select', 'id' => $client["id"])); ?>">consult</a>

                            </td>                      
                        </tr>
                <?php endforeach;
            } ?>
        </table>
        <div class="extrabottom">
<?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  
