<?php $acl = Login_Model_Acl::getInstance(); ?>
<div class="container">



    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Supplier")); ?></h1>



    </div>
    <div class="contentbox">
        <table width="100%">
            <thead> 
                <tr>
                    <th><?php echo $this->translate('Company name'); ?></th>
                    <th><?php echo $this->translate('Fiscal name'); ?></th>
                    <th><?php echo $this->translate('Type'); ?></th>
                    <th><?php echo $this->translate('Telephone'); ?></th>
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('City'); ?></th>
                    <th><?php echo $this->translate('Activitys'); ?></th>
                    <th><?php echo $this->translate('Description'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>
                </tr>
            </thead>

            <tbody>

                <tr>
                    <td><?php echo $this->escape($this->select_supplier['name']); ?></td>                         
                    <td><?php echo $this->escape($this->select_supplier['fiscal_name']); ?></td>
                    <td><?php echo $this->escape($this->select_supplier['company_types_name']); ?></td> 
                    <td><?php echo $this->escape($this->select_supplier['telephone']); ?></td>
                    <td><?php echo $this->escape($this->select_supplier['email']); ?></td>
                    <td><?php echo $this->escape($this->select_supplier['city']); ?></td>
                    <td><?php echo $this->escape($this->select_supplier['activity_types_name']); ?></td>
                    <td><?php echo $this->escape($this->select_supplier['observation']); ?></td>
                    <td>

                        <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:productionsuppliers", "edit")) { ?>
                            <a href="<?php echo $this->url(array('controller' => 'productionsuppliers', 'action' => 'edit')); ?>">
                                <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                        <?php } ?>

                    </td>        
                </tr>
        </table>

    </div>
</div>
<!-- Table supplier end -->  
<!-- Table contacts -->  


<div class="container">
    <div class="conthead">
        <h1><?php echo $this->translate("Contacts - Supplier"); ?></h1>
        <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:contactresource", "add")) { ?>
            <p><a href="<?php echo $this->url(array('controller' => 'contactresource', 'action' => 'add'));
            ?>">Add Contact</a></p>
            <?php } ?> 

    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>

                <tr>
                    <th><?php echo $this->translate('Contact name'); ?></th>
                    <th><?php echo $this->translate('Company name'); ?></th>
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('telephone'); ?></th>
                    <th><?php echo $this->translate('direction'); ?></th>
                    <th><?php echo $this->translate('User'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->paginator as $contact) : ?>
                    <tr>
                        <td><?php echo $this->escape($contact["name"]); ?></td>                         
                        <td><?php echo $this->escape($contact["company"]); ?></td>                         
                        <td><?php echo $this->escape($contact["email"]); ?></td>
                        <td><?php echo $this->escape($contact["telephone"]); ?></td>
                        <td><?php echo $this->escape($contact["direction"]); ?></td>
                        <td><?php if ($contact["acl_users_id"] == 0) { ?>
                                NO tiene usuario
                            <?php } else { ?>
                                tiene usuario
                            <?php } ?>
                        </td>
                        <td>
                            <?php if (!$contact['in_litter']) { ?>
                                <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:contactresource", "edit")) { ?>
                                    <a href="<?php echo $this->url(array('controller' => 'contactresource', 'action' => 'edit', 'id' => $contact["id"])); ?>">
                                        <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                                <?php } ?>

                                 <?php } ?>   
                            



                        </td>                        
                    </tr>
                <?php endforeach; ?>
        </table>
        <div class="extrabottom">
            <?php echo $this->paginator_contact; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  

<!-- Table resource -->
<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Resources - Supplier")); ?></h1>
        <p> <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:resource", "addresourcesupplier")) { ?>
                <a href="<?php
                echo $this->url(array('controller' => 'resource',
                    'action' => 'addresourcesupplier'));
                ?>">Add new resource</a></p>
            <?php } ?> 



    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>

                <tr>
                    <th><?php echo $this->translate('name'); ?></th>
                    <th><?php echo $this->translate('type'); ?></th>
                    <th><?php echo $this->translate('direction'); ?></th>                   
                    <th><?php echo $this->translate('quantity'); ?></th>
                    <th><?php echo $this->translate('description'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php
                if ($this->paginator_resource) {
                    foreach ($this->paginator_resource as $resource) :
                        ?>
                        <tr>
                            <td><?php echo $this->escape($resource->name); ?></td>
                            <td><?php echo $this->escape($resource->resource_types_name); ?></td>
                            <td><?php echo $this->escape($resource->direction); ?></td>
                            <td><?php echo $this->escape($resource->num_resources); ?></td>
                            <td><?php echo $this->escape($resource->description); ?></td>

                            <td>

                                <?php if (!$resource->in_litter) { ?>
                                    <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:resource", "editresourcesupplier")) { ?>
                                        <a href="<?php echo $this->url(array('controller' => 'resource', 'action' => 'editresourcesupplier', 'id' => $resource->id)); ?>">
                                            <img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>

                                    <?php } ?>


                                <?php } ?>    

                            </td>                        
                        </tr>
                        <?php
                    endforeach;
                }
                ?>
        </table>
        <div class="extrabottom">
            <?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table resource end -->  
