<?php $acl = Login_Model_Acl::getInstance(); ?>          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Production supplier")); ?></h1>
        <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:productionsuppliers", "add")) { ?>
            <p><a href="<?php echo $this->url(array('controller' => 'productionsuppliers', 'action' => 'add'));
            ?>"><?php echo $this->translate("Add Production Suppliers") ?>

                </a></p>
        <?php } ?> 
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>

                <tr>
                    <th><?php echo $this->translate('name'); ?></th>

                    <th><?php echo $this->translate('Actions'); ?></th>

                </tr>
            </thead>

            <tbody>
                <?php
                if ($this->paginator) {
                    foreach ($this->paginator as $supplier) :
                        ?>
                        <tr>
                            <td><?php echo $this->escape($supplier["name"]); ?></td>

                            <td>
                                <?php if ($acl->isUserAllowed($_SESSION["gpms"]["role"], "production:productionsuppliers", "select")) { ?>
                                <a href="<?php echo $this->url(array('controller' => 'productionsuppliers', 'action' => 'select', 'id' => $supplier["id"])); ?>">consult</a>
                                <?php } ?>
                                
                            </td>                      
                        </tr>
                    <?php
                    endforeach;
                }
                ?>
        </table>
        <div class="extrabottom">
<?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  
