<div class="container">
    <div class="conthead">

        <h2>Add new Model</h2>
    </div>
    <div class="contentbox">
        <div class="inputboxes">
            <label>Upload: </label>

            <input name="" type="file" /> <img src="images/loading.gif" alt="Loading" />
        </div>

        <?php
        $this->title = "Add new Model";
        $this->headTitle($this->title);
        
        echo $this->form;
        ?>

    </div>
</div>