          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Financess")); ?></h1>
        <p><a href="<?php
echo $this->url(array('controller' => 'finances',
    'action' => 'add'));
?>">Add new finances</a></p>

    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>
                    <th><?php echo $this->translate('Resource'); ?></th>
                    <th><?php echo $this->translate('Activity'); ?></th>
                    <th><?php echo $this->translate('data start'); ?></th>
                    <th><?php echo $this->translate('data end'); ?></th>
                    <th><?php echo $this->translate('unbilled_hours'); ?></th>
                    <th><?php echo $this->translate('price supplier'); ?></th>
                    <th><?php echo $this->translate('quantity'); ?></th>
                    <th><?php echo $this->translate('iva'); ?></th>
                    <th><?php echo $this->translate('status'); ?></th>
                    <th><?php echo $this->translate('facturation_type'); ?></th>
                    <th><?php echo $this->translate('price'); ?></th>
                    <th><?php echo $this->translate('final price'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $finances) : ?>
                    <tr>
                        <td><?php echo $this->escape($finances->name); ?></td>                         
                        <td><?php echo $this->escape($finances->activity_name); ?></td>
                        <td><?php echo $this->escape($finances->date_start); ?></td>
                        <td><?php echo $this->escape($finances->date_end); ?></td>
                        <td><?php echo $this->escape($finances->unbilled_hours); ?></td>
                        <td><?php echo $this->escape($finances->price); ?></td>
                        <td><?php echo $this->escape($finances->quantity); ?></td>
                        <td><?php echo $this->escape($finances->iva_type_name); ?></td>
                       
                        <td><?php echo $this->escape($finances->invoices_status_name); ?></td>
                        <td><?php echo $this->escape($finances->facturation_types_name);?></td>
                       
                        <td><?php echo $this->escape($finances->receipt_price);  ?></td>
                        <td><?php echo $this->escape($finances->final_price);  ?></td>
                        <td>
                            
                            <?php  if ($finances->invoice_id) { ?>
                            FACTURADA   
                            <?php } elseif(! $finances->resources_activities_has_receipt_id) { ?>
                              <a href="<?php echo $this->url(array('controller' => 'finances', 'action' => 'addreceipt', 'id' => $finances->id)); ?>">
                                    <img src="/styles/images/icons/icon_arrow.png" alt="Add Facture" /></a>
                            <?php } else {?>
                            Añadida pendiente de facturar
                            <a href="<?php echo $this->url(array('controller' => 'finances', 'action' => 'delete', 'id' => $finances->id)); ?>">
                                 <img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                                <?php }?>
                            
                        </td>                        
                    </tr>
                <?php endforeach; ?>
        </table>
        <div class="extrabottom">
            <?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  


<!-- EOF Advertencia de borrado de Idioma -->
<script type="text/javascript">

    window.managementfacturation = {
        // Cambia la Publicación
        changeFacturationResource: function (oArgs) {
	    	
            var elementId = 'elementId' in oArgs ? oArgs.elementId : undefined;
            if ('undefined' != typeof(elementId)) {
                jQuery.post("/finances/finances/addFacturationAjax/id/<?php echo $this->elementId; ?>/format/json",
                {elementId: elementId},
                function (data) {
                    jQuery("#videos_at").trigger("reloadGrid");
                }
            );
            }
        }
	    
	    
    };
</script>