          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("Finances")); ?></h1>
        <p><a href="<?php
echo $this->url(array('controller' => 'invoices',
    'action' => 'add'));
?>"><?php echo $this->escape($this->translate("Crear Factura")); ?></a></p>

        <p><a href="<?php
              echo $this->url(array('controller' => 'invoices',
                  'action' => 'index'));
?>"><?php echo $this->escape($this->translate("Consultar Facturas")); ?></a></p>
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>
                    <th><?php echo $this->translate('Resource'); ?></th>
                    <th><?php echo $this->translate('Activity'); ?></th>
                    <th><?php echo $this->translate('data start'); ?></th>
                    <th><?php echo $this->translate('data end'); ?></th>
                    <th><?php echo $this->translate('unbilled_hours'); ?></th>
                    <th><?php echo $this->translate('price supplier'); ?></th>
                    <th><?php echo $this->translate('quantity'); ?></th>
                    <th><?php echo $this->translate('iva'); ?></th>
                    <th><?php echo $this->translate('status'); ?></th>
                    <th><?php echo $this->translate('facturation_type'); ?></th>
                    <th><?php echo $this->translate('price Activity/Hour'); ?></th>
                    <th><?php echo $this->translate('Total Price'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $finances) : ?>
                    <tr id ="<?php echo $this->escape($finances->id); ?>">
                        <td><?php echo $this->escape($finances->resource_name); ?></td>                         
                        <td><?php echo $this->escape($finances->activity_name); ?></td>
                        <td><?php echo $this->escape($finances->date_start); ?></td>
                        <td><?php echo $this->escape($finances->date_end); ?></td>
                        <td><?php echo $this->escape($finances->unbilled_hours); ?></td>
                        <td><?php echo $this->escape($finances->price); ?></td>
                        <td><?php echo $this->escape($finances->quantity); ?></td>
                        <td><?php echo $this->escape($finances->iva_type_name); ?></td>

                        <td><?php echo $this->escape($finances->invoices_status_name); ?></td>
                        <?php if (!$finances->resources_activities_has_receipt_id) { ?>
                            <td class ="facturation_type">
                                <select  width=" 150px">
                                    <?php
                                    foreach ($this->iva_type as $key => $value)
                                        echo "<option value='$key'>$value</option>";
                                    ?>
                                </select>
                            </td>
                        <?php } else { ?>
                            <td> 
                                <?php echo $this->escape($finances->facturation_types_name); ?>
                            </td>
                        <?php } ?>

                        <?php if (!$finances->resources_activities_has_receipt_id) { ?>
                            <td class ="price">
                                <input type="text" value="0"/> 
                            </td>
                        <?php } else { ?>
                            <td> 
                                <?php echo $this->escape($finances->price); ?>

                            </td> 

                        <?php } ?>
                        <?php if (!$finances->resources_activities_has_receipt_id) { ?>   
                            <td class ="final_price"> 

                            </td>
                        <?php } else { ?>
                            <td>
                                <?php echo $this->escape($finances->final_price); ?>
                            </td>
                        <?php } ?>



                        <?php if ($finances->invoice_id) { ?>
                            <td>
                                <?php echo $this->translate('Facturado nº fac : ' . $finances->invoice_id); ?>
                            </td>
                        <?php } elseif (!$finances->resources_activities_has_receipt_id) { ?>
                            <td class ="mod_receipt">
                                <input type="button"  class="addbyajax" value="Añadir a factura" />
                            </td>
                        <?php } else { ?>
                            <td>
                                <a href="<?php echo $this->url(array('controller' => 'finances', 'action' => 'delete', 'id' => $finances->resources_activities_has_receipt_id)); ?>">
                                    <input type="button" value="Quitar de Factura" />
                            </td>
                        <?php } ?>


                    </tr>
                <?php endforeach; ?>
        </table>
        <div class="extrabottom">
            <?php echo $this->paginator; ?>          

        </div>
    </div>
</div>

<!-- Table styles end -->  
<?php echo $this->datePicker('dp','',array()); ?>
<script type="text/javascript">
    $(document).ready(function(){
        //cuando hago clic en el boton id=veralbumes
        $('.addbyajax').click(function(){
            idrow= $(this).parent().parent().attr("id"),
            price = $('#'+idrow+' .price input').val(),
            facturation_type = $('#'+idrow+' .facturation_type select').val(),
            facturation_type_name = $('#'+idrow+' select option:selected').html(),
            url = "/finances/finances/addreceipt/id/"+idrow+"/price/"+price+"/facturation_type/"+facturation_type+"/facturation_type_name/"+facturation_type_name                  
            id = "",
            final_price = "",             
            mod_receipt = ""           
            ;
           
            //funcion que hace llamada a ajax esperando un
            // arreglo json de respuesta
            $.getJSON(url,  function(data)
            {
               
                //por cada elemento
                //(recordar que recibimos un arreglo de arreglos)
                $.each(data, function(i,row){
                    //                    guardo sus datos en un texto
                    switch (i){
                        case 'id' :
                            id = row;
                            break
                                        
                        case 'final_price':
                            final_price = row;
                            break
                                    
                                   
                    }
                    //                                 
                });
                mod_receipt = "<a href='/finances/finances/delete/id/"+id+"'> <input type='button' class='deletebyajax' value='Quitar de Factura' /> </a>"                           
                       
                $('#'+idrow+' .facturation_type').html(facturation_type_name);
                $('#'+idrow+' .price').html(price);
                $('#'+idrow+' .final_price').html(final_price);
                $('#'+idrow+' .mod_receipt').html(mod_receipt).removeAttr("id").attr('id', 'itemreceiptid'+id);
                            
            });
        });
         
    });
</script>
