          

<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Companys")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'company',
    'action' => 'add')); ?>">Add new company</a></p>
        <ul id="topbtns">
            	<li>
                	<a href="<?php echo $this->url(array('module' => 'company','controller' => 'role','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_calendar.png" alt="Role" /><br />role</a>
                </li>
                <li>
                        <a href="<?php echo $this->url(array('module' => 'company','controller' => 'company','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_user.png" alt="Companys" /><br />Companys</a>
                
                </li>
                <li>
                	<a href="<?php echo $this->url(array('module' => 'company','controller' => 'permission','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_create.png" alt="Permission" /><br />Permission  </a>
                </li>
               
                <li>
                	<a href="<?php echo $this->url(array('module' => 'company','controller' => 'resource','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_support.png" alt="Resource" /><br />Resource</a>
                </li>                
            </ul>
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>
                    
                </tr>
                                    
                <tr>
                    <th><?php echo $this->translate('Company name'); ?></th>
                    <th><?php echo $this->translate('Date'); ?></th>
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('Status'); ?></th>
                    <th><?php echo $this->translate('Person_id?'); ?></th>
                    <th><?php echo $this->translate('Validation code'); ?></th>
                    <th><?php echo $this->translate('Phone'); ?></th>
                    <th><?php echo $this->translate('Role'); ?></th>
                    <th><?php echo $this->translate('Actions'); ?></th>
                    
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->paginator as $company) : ?>
                    <tr>
                        <td><?php echo $this->escape($company->name); ?></td>                         
                        <td><?php echo $this->escape($company->date); ?></td>
                        <td><?php echo $this->escape($company->email); ?></td>
                        <td><?php echo $this->escape($company->status); ?></td>
                        <td><?php echo $this->escape($company->person_id); ?></td>
                        <td><?php echo $this->escape($company->validation_code); ?></td>
                        <td><?php echo $this->escape($company->phone); ?></td>
                        <td><?php echo $this->escape($company->role); ?></td>               
                        <td>
                            <a href="<?php echo $this->url(array('controller' => 'company','action' => 'edit', 'id' => $company->id)); ?>">
                            	<img src="/styles/images/icons/icon_edit.png" alt="Edit" /></a>
                            <a href="<?php echo $this->url(array('controller' => 'company','action' => 'delete', 'id' => $company->id)); ?>">
                            	<img src="/styles/images/icons/icon_delete.png" alt="Delete" /></a>
                        </td>                        
                    </tr>
                <?php endforeach; ?>
        </table>
       <div class="extrabottom">
            <?php echo $this->paginator; ?>           
        </div>
    </div>
</div>
<!-- Table styles end -->  
