<?php
$this->title = "Delete Activity";
$this->headTitle($this->title);
?>
<p>Are you sure that you want delete
    '<?php echo $this->escape($this->activity['id']); ?>' ?
    
</p>
<form action="<?php echo $this->url(array('action' => 'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->activity['id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>
