<div class="container">
    <div class="conthead">
        <h1><?php echo $this->escape($this->translate("My Modules")); ?></h1>
        <p><a href="<?php echo $this->url(array('controller' => 'index',
    'action' => 'add')); ?>">Add new module</a></p>
        <ul id="topbtns">
            	<li>
                	<a href="<?php echo $this->url(array('module' => 'user','controller' => 'role','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_calendar.png" alt="Role" /><br />role</a>
                </li>
                <li>
                        <a href="<?php echo $this->url(array('module' => 'user','controller' => 'index','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_user.png" alt="Users" /><br />Users</a>
                
                </li>
                <li>
                	<a href="<?php echo $this->url(array('module' => 'user','controller' => 'permission','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_create.png" alt="Permission" /><br />Permission  </a>
                </li>
                <li>
                	<a href="<?php echo $this->url(array('module' => 'user','controller' => 'module','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_media.png" alt="Module" /><br />Module</a>
                </li>
                <li>
                	<a href="<?php echo $this->url(array('module' => 'user','controller' => 'resource','action' => 'index')); ?>"><img src="/styles/images/icons/icon_lrg_support.png" alt="Resource" /><br />Resource</a>
                </li>                
            </ul>
    </div>
    <div class="contentbox">
        <table width="100%">
            <thead>
                <tr>
                    <th><?php echo $this->translate('Module Folders'); ?></th>                    
                    <th><?php echo $this->translate('Status'); ?></th>
                    <th><?php echo $this->translate('Installation'); ?></th>
                    <th><?php echo $this->translate('Options'); ?></th>
                </tr>
            </thead>

            <tbody>
                
                 <?php foreach ($this->modules as $module) : ?>
                    
                    <tr>
                        <td><?php echo $this->escape($module["name"]); ?></td>
                        <td><?php if ($module['active']){
                                    echo "activado"; 
                                  }else{
                                    echo "desactivado";
                                    
                                  };?>
                        </td>
                        <td><?php 
                               if ($module["install"]){     
                                    echo "instalado";
                                }else{
                                    echo "desinstalado";
                                };
                             ?></td>
                        <td>
                            <?php                            
                            if (!$module["install"]) {
                            ?>                                                
                                <a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'install', 'module_name' => $module["name"])); ?>">
                                install</a>
                          
                                <a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'delete', 'module_name' => $module["name"])); ?>">
                                <img src="/styles/images/icons/icon_delete.png" alt="Delete" />delete</a>            
                                
                                <a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'backup', 'module_name' => $module["name"])); ?>">
                                Backup</a>            
                                
                                <?php
                            } else {
                                ?>
                                <a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'edit', 'module_name' => $module["name"])); ?>">
                                <img src="/styles/images/icons/icon_edit.png" alt="Edit" />editar</a>

                                <a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'desinstall', 'id' => $module["id"])); ?>">
                                desintalar</a>
                                 
                                <?php if ($module['active']){
                                ?>
                                
                                <a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'deactivate', 'id' => $module['id'])); ?>">
                                desactivar </a>
                                <?php    
                                }else{                                        
                                ?>                
                                <a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'activate', 'id' => $module['id'])); ?>">
                                activar </a>
                                
                                <?php
                                                                    
                                }?>
                                <a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'backup', 'module_name' => $module["name"])); ?>">
                                Backup</a>
                                <?php
                                
                            }
                            ?>                                                     
                        </td>                    
                    </tr>
                    
        <?php endforeach; ?>
                
        </table>
        <div class="extrabottom">
            <ul class="pagination">
                <li class="text">Previous</li>
                <li class="page"><a href="#" title="">1</a></li>
                <li><a href="#" title="">2</a></li>
                <li><a href="#" title="">3</a></li>
                <li><a href="#" title="">4</a></li>
                <li class="text"><a href="#" title="">Next</a></li>
            </ul>
            <div class="bulkactions">
                <select>
                    <option>Select bulk action...</option>
                </select>
                <input type="submit" value="Apply" class="btn" />
            </div>
        </div>
    </div>
</div>
<!-- Table styles end -->  
