 <?php //TODO crear el element->getImages?>
<div class="inputcontainer">
 
  
   <!--<img src="/styles/images/icons/icon_username.png" alt="Username" />-->
    <label for="username"><?=$this->translate($this->element->getLabel());?>:</label>
    <?= $this->{$this->element->helper}(
                $this->element->getName(),
                $this->element->getValue(),
                $this->element->getAttribs()
    ) ?>	
</div>
